"""add email verification fields to user

Revision ID: ab1bb0e8752a
Revises: f953d9502fa1
Create Date: 2025-05-03 16:36:44.431040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1bb0e8752a'
down_revision: Union[str, None] = 'f953d9502fa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('doctor_profiles_ibfk_1', 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('patient_profiles_ibfk_1', 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('email_verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email_verification_token_created_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email_verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email_verification_token_created_at')
    op.drop_column('users', 'email_verification_token')
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.create_foreign_key('patient_profiles_ibfk_1', 'patient_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'doctor_profiles', type_='foreignkey')
    op.create_foreign_key('doctor_profiles_ibfk_1', 'doctor_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
